### ISSUE TITLE
pip install purepng fails on pypy3

### ISSUE THREAD

**Issue by brechtm** [Scondo/purepng#17]
Works with pypy2 though.

    $ pip install purepng
    DEPRECATION: --download-cache has been deprecated and will be removed in the future. Pip now automatically uses and configures its cache.
    Collecting purepng
      Using cached purepng-0.1.1.zip
    Building wheels for collected packages: purepng
      Running setup.py bdist_wheel for purepng
      Complete output from command /Users/brechtm/.pyenv/versions/rinoh-pypy3/bin/python -c "import setuptools;__file__='/private/var/folders/cm/h_fnh5lx0b5b1b6wvnlc7qlw0000gn/T/pip-build-lev6mq/purepng/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /var/folders/cm/h_fnh5lx0b5b1b6wvnlc7qlw0000gn/T/tmptuuff1pip-wheel-:
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.10-x86_64-3.2
      creating build/lib.macosx-10.10-x86_64-3.2/png
      copying code/png/__init__.py -> build/lib.macosx-10.10-x86_64-3.2/png
      copying code/png/png.py -> build/lib.macosx-10.10-x86_64-3.2/png
      copying code/png/PngImagePlugin.py -> build/lib.macosx-10.10-x86_64-3.2/png
      running build_ext
      building 'pngfilters' extension
      creating build/temp.macosx-10.10-x86_64-3.2
      creating build/temp.macosx-10.10-x86_64-3.2/code
      creating build/temp.macosx-10.10-x86_64-3.2/code/png
      cc -arch x86_64 -O2 -fPIC -Wimplicit -I/Users/brechtm/.pyenv/versions/rinoh-pypy3/include -c code/png/pngfilters.c -o build/temp.macosx-10.10-x86_64-3.2/code/png/pngfilters.o
      code/png/pngfilters.c:58:9: warning: 'Py_OptimizeFlag' macro redefined [-Wmacro-redefined]
      #define Py_OptimizeFlag 0
              ^
      /Users/brechtm/.pyenv/versions/rinoh-pypy3/include/pypy_macros.h:594:9: note: previous definition is here
      #define Py_OptimizeFlag PyPy_OptimizeFlag
              ^
      code/png/pngfilters.c:131:11: warning: 'Py_TPFLAGS_CHECKTYPES' macro redefined [-Wmacro-redefined]
        #define Py_TPFLAGS_CHECKTYPES 0
                ^
      /Users/brechtm/.pyenv/versions/rinoh-pypy3/include/object.h:411:9: note: previous definition is here
      #define Py_TPFLAGS_CHECKTYPES (1L<<4)
              ^
      code/png/pngfilters.c:132:11: warning: 'Py_TPFLAGS_HAVE_INDEX' macro redefined [-Wmacro-redefined]
        #define Py_TPFLAGS_HAVE_INDEX 0
                ^
      /Users/brechtm/.pyenv/versions/rinoh-pypy3/include/object.h:448:9: note: previous definition is here
      #define Py_TPFLAGS_HAVE_INDEX (1L<<17)
              ^
      code/png/pngfilters.c:135:11: warning: 'Py_TPFLAGS_HAVE_NEWBUFFER' macro redefined [-Wmacro-redefined]
        #define Py_TPFLAGS_HAVE_NEWBUFFER 0
                ^
      /Users/brechtm/.pyenv/versions/rinoh-pypy3/include/object.h:458:9: note: previous definition is here
      #define Py_TPFLAGS_HAVE_NEWBUFFER (1L<<21)
              ^
      code/png/pngfilters.c:267:11: warning: 'PyMethod_New' macro redefined [-Wmacro-redefined]
        #define PyMethod_New(func, self, klass) ((self) ? PyMethod_New(func, self) : PyInstanceMethod_New(func))
                ^
      /Users/brechtm/.pyenv/versions/rinoh-pypy3/include/pypy_macros.h:36:9: note: previous definition is here
      #define PyMethod_New PyPyMethod_New
              ^
      code/png/pngfilters.c:18570:36: error: no member named 'curexc_traceback' in 'struct _ts'
              PyObject* tmp_tb = tstate->curexc_traceback;
                                 ~~~~~~  ^
      code/png/pngfilters.c:18573:21: error: no member named 'curexc_traceback' in 'struct _ts'
                  tstate->curexc_traceback = tb;
                  ~~~~~~  ^
      5 warnings and 2 errors generated.
      error: command 'cc' failed with exit status 1
    
      ----------------------------------------
      Failed building wheel for purepng
    Failed to build purepng
    Installing collected packages: purepng
      Running setup.py install for purepng
        Complete output from command /Users/brechtm/.pyenv/versions/rinoh-pypy3/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/cm/h_fnh5lx0b5b1b6wvnlc7qlw0000gn/T/pip-build-lev6mq/purepng/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/cm/h_fnh5lx0b5b1b6wvnlc7qlw0000gn/T/pip-wfh6ls-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/brechtm/.pyenv/versions/rinoh-pypy3/include/site/python3.2/purepng:
        running install
        running build
        running build_py
        running build_ext
        building 'pngfilters' extension
        cc -arch x86_64 -O2 -fPIC -Wimplicit -I/Users/brechtm/.pyenv/versions/rinoh-pypy3/include -c code/png/pngfilters.c -o build/temp.macosx-10.10-x86_64-3.2/code/png/pngfilters.o
        code/png/pngfilters.c:58:9: warning: 'Py_OptimizeFlag' macro redefined [-Wmacro-redefined]
        #define Py_OptimizeFlag 0
                ^
        /Users/brechtm/.pyenv/versions/rinoh-pypy3/include/pypy_macros.h:594:9: note: previous definition is here
        #define Py_OptimizeFlag PyPy_OptimizeFlag
                ^
        code/png/pngfilters.c:131:11: warning: 'Py_TPFLAGS_CHECKTYPES' macro redefined [-Wmacro-redefined]
          #define Py_TPFLAGS_CHECKTYPES 0
                  ^
        /Users/brechtm/.pyenv/versions/rinoh-pypy3/include/object.h:411:9: note: previous definition is here
        #define Py_TPFLAGS_CHECKTYPES (1L<<4)
                ^
        code/png/pngfilters.c:132:11: warning: 'Py_TPFLAGS_HAVE_INDEX' macro redefined [-Wmacro-redefined]
          #define Py_TPFLAGS_HAVE_INDEX 0
                  ^
        /Users/brechtm/.pyenv/versions/rinoh-pypy3/include/object.h:448:9: note: previous definition is here
        #define Py_TPFLAGS_HAVE_INDEX (1L<<17)
                ^
        code/png/pngfilters.c:135:11: warning: 'Py_TPFLAGS_HAVE_NEWBUFFER' macro redefined [-Wmacro-redefined]
          #define Py_TPFLAGS_HAVE_NEWBUFFER 0
                  ^
        /Users/brechtm/.pyenv/versions/rinoh-pypy3/include/object.h:458:9: note: previous definition is here
        #define Py_TPFLAGS_HAVE_NEWBUFFER (1L<<21)
                ^
        code/png/pngfilters.c:267:11: warning: 'PyMethod_New' macro redefined [-Wmacro-redefined]
          #define PyMethod_New(func, self, klass) ((self) ? PyMethod_New(func, self) : PyInstanceMethod_New(func))
                  ^
        /Users/brechtm/.pyenv/versions/rinoh-pypy3/include/pypy_macros.h:36:9: note: previous definition is here
        #define PyMethod_New PyPyMethod_New
                ^
        code/png/pngfilters.c:18570:36: error: no member named 'curexc_traceback' in 'struct _ts'
                PyObject* tmp_tb = tstate->curexc_traceback;
                                   ~~~~~~  ^
        code/png/pngfilters.c:18573:21: error: no member named 'curexc_traceback' in 'struct _ts'
                    tstate->curexc_traceback = tb;
                    ~~~~~~  ^
        5 warnings and 2 errors generated.
        error: command 'cc' failed with exit status 1
    
        ----------------------------------------
    Command "/Users/brechtm/.pyenv/versions/rinoh-pypy3/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/cm/h_fnh5lx0b5b1b6wvnlc7qlw0000gn/T/pip-build-lev6mq/purepng/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/cm/h_fnh5lx0b5b1b6wvnlc7qlw0000gn/T/pip-wfh6ls-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/brechtm/.pyenv/versions/rinoh-pypy3/include/site/python3.2/purepng" failed with error code 1 in /private/var/folders/cm/h_fnh5lx0b5b1b6wvnlc7qlw0000gn/T/pip-build-lev6mq/purepng

**Comment by Scondo** [comment]
It looks like bug of compatibility between Cython and PyPy..

I'll try to find way how to make usage of pre-cythonized files optional or disable it.
https://github.com/Scondo/purepng/blob/master/setup.py#L93

**Comment by Scondo** [comment]
I remove `pngfilters.c` from source distribution as workaround, but can't test as pypy3 fails on my Windows 10.
Could you check please?

**Comment by brechtm** [comment]
I assume you updated `purepng-0.1.1.tar.gz` on PyPI?
`pip install purepng` in a pypy3 venv works fine for me now. Thanks!
