### ISSUE TITLE
ImportError: No module named 'unimport'

### ISSUE THREAD

**Issue by ChlorideCull** [Scondo/purepng#18]
When instaling with pip, I get this error:

    Collecting purepng<0.2.0,>=0.1.1 (from -r requirements.txt (line 1))
      Using cached purepng-0.1.1.tar.gz
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/tmp/pip-build-n0fqd754/purepng/setup.py", line 89, in <module>
            from unimport import do_unimport
        ImportError: No module named 'unimport'

Running Python 3.5.1, with the following packages installed in pip

    binwalk (2.1.1)
    chardet (2.3.0)
    Cython (0.23.4)
    iotop (0.6)
    packaging (16.2)
    pip (8.0.2)
    PyBluez (0.20)
    pygobject (3.18.2)
    pyparsing (2.1.0)
    requests (2.9.1)
    setuptools (20.1.1)
    six (1.10.0)
    team (1.0)
    urllib3 (1.14)

**Comment by ChlorideCull** [comment]
The issue is probably that the file isn't inside the tar in the first place, haha

![](http://i.imgur.com/NQbzL7l.png)

**Comment by Scondo** [comment]
Try 0.1.2 (0.1.2.1 as one bug was found during build process)
