### ISSUE TITLE
FormatError: PNG file has invalid signature.

### ISSUE THREAD

**Issue by 0joshuaolson1** [Scondo/purepng#23]
Chrome shows the file fine.

**Comment by Scondo** [comment]
Could you provide exact file?

**Comment by 0joshuaolson1** [comment]
Here ya go: https://drive.google.com/open?id=0BwbzZs3ta3O-T0JTUndVTXJCOE0

**Comment by 0joshuaolson1** [comment]
This applies to PyPNG too, fyi.

**Comment by Scondo** [comment]
And will apply to any PNG library.
It's not PNG file. It is a JPEG file with extension '.png'.
So any generic image viewer which does not rely on extension (incl. web browsers) will parse and show this, but any PNG-specific library will not.

**Comment by 0joshuaolson1** [comment]
Oh, it seems I can't trust a certain tool. Sorry!
